parameters:
#    msi_search.example.class: Msi\SearchBundle\Example

services:
#    msi_search.example:
#        class: %msi_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
